/**
 * GENERATED by gas/scripts/package-apps-script.mjs — do not edit by hand.
 * Regenerate with: npm run harbor:build
 */

var BUNDLE_CHUNKS = ["Bundle0","Bundle1","Bundle2","Bundle3"];

var FONT_URLS = [];

var BUILD_STAMP = "2026-08-31T01:43:30.148Z";
