/**
 * GENERATED by gas/scripts/package-apps-script.mjs — do not edit by hand.
 *
 * Both lists are read out of the shared source at build time, so the Harbor
 * build cannot fall behind the public one. Edit src/lib/constants.ts (for the
 * allowlist) or add a page under src/app (for a route), then rebuild.
 */

// Every route this build publishes. doGet matches ?page= against this list,
// because the value is interpolated into a script tag.
var PUBLISHED_ROUTES = [
  "/",
  "/agentic-ai",
  "/agentic-ai/skills",
  "/ai-basics",
  "/ai-basics/core-concepts",
  "/ai-basics/how-it-works",
  "/ai-basics/innovation",
  "/ai-basics/models",
  "/ai-basics/strengths",
  "/choose-your-claude",
  "/claude-cowork",
  "/context-engineering",
  "/prompt-builder",
  "/prompt-engineering",
  "/resources",
  "/right-size-your-model",
  "/road-to-agentic-engineering",
  "/road-to-agentic-engineering/champions",
  "/road-to-agentic-engineering/cheatsheet",
  "/road-to-agentic-engineering/fundamentals",
  "/road-to-agentic-engineering/installation",
  "/road-to-agentic-engineering/setup",
  "/road-to-agentic-engineering/tips",
  "/road-to-agentic-engineering/workflows",
  "/use-cases",
  "/vibe-coding",
  "/vibe-coding/champions",
  "/vibe-coding/cheatsheet",
  "/vibe-coding/fundamentals",
  "/vibe-coding/installation",
  "/vibe-coding/setup",
  "/vibe-coding/tips",
  "/vibe-coding/workflows"
];

// The 25 routes that are real content and get a Harbor page.
// The remainder are redirect stubs for the section's former name.
var CONTENT_ROUTES = [
  "/",
  "/agentic-ai",
  "/agentic-ai/skills",
  "/ai-basics",
  "/ai-basics/core-concepts",
  "/ai-basics/how-it-works",
  "/ai-basics/innovation",
  "/ai-basics/models",
  "/ai-basics/strengths",
  "/choose-your-claude",
  "/claude-cowork",
  "/context-engineering",
  "/prompt-builder",
  "/prompt-engineering",
  "/resources",
  "/right-size-your-model",
  "/road-to-agentic-engineering",
  "/road-to-agentic-engineering/champions",
  "/road-to-agentic-engineering/cheatsheet",
  "/road-to-agentic-engineering/fundamentals",
  "/road-to-agentic-engineering/installation",
  "/road-to-agentic-engineering/setup",
  "/road-to-agentic-engineering/tips",
  "/road-to-agentic-engineering/workflows",
  "/use-cases"
];

var CHAMPION_EMAILS = [
  "abigail.fassbender@coverwhale.com",
  "bryan.glenn@coverwhale.com",
  "bryan.salvadore@coverwhale.com",
  "charisse.skeete@coverwhale.com",
  "daniel.medina@coverwhale.com",
  "david.castellanos@coverwhale.com",
  "ian@coverwhale.com",
  "jose.selemi@coverwhale.com",
  "ken@coverwhale.com",
  "kevin@coverwhale.com",
  "lennie.cohen@coverwhale.com",
  "mercedes.mojica@coverwhale.com",
  "sabina.atkinson@coverwhale.com",
  "sam.englander@coverwhale.com",
  "sean.johnson@coverwhale.com",
  "william.fahrner@coverwhale.com"
];
